--- 
- hosts: localhost
  gather_facts: no
  become: no
  vars:
    counter: 4
  tasks:
    - name: generate empty in each 10 sec
      file:
        path: "/tmp/playing_opera/ope_ex4/loopdemo/file{{ item }}"
        state: touch
      loop: [ 0, 1, 2, 3, 4, 5, 6, 7]
      when: item < 4
...
